# Script to fix garbled Japanese text in MainWindowViewModel.cs
$filePath = "c:\Users\keisu\source\repos\PileDesign_0\Graphics_r1\ViewModels\MainWindowViewModel.cs"

# Read the file content
$content = Get-Content -Path $filePath -Raw -Encoding UTF8

# Apply replacements in order (most specific first to avoid partial matches)
# Comments and XML documentation
$content = $content -replace '// ・ｽ・ｽ: ・ｽt・ｽB・ｽ\[・ｽ・ｽ・ｽh・ｽ骭ｾ・ｽ・ｽﾏ更', '// 追加: フィールド宣言の変更'
$content = $content -replace 'SoilPiles ・ｽﾌ撰ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽf・ｽo・ｽE・ｽ・ｽ・ｽX・ｽt・ｽ・ｽ・ｽﾅ・ｿｽ・ｽN・ｽG・ｽX・ｽg・ｽ・ｽ・ｽﾜゑｿｽ・ｽB', 'SoilPiles の生成をデバウンスでリクエストします。'
$content = $content -replace '・ｽZ・ｽ・ｽ・ｽﾔに包ｿｽ・ｽ・ｽ・ｽ・ｽﾄばゑｿｽﾄゑｿｽ・ｽA・ｽﾅ鯉ｿｽﾌ呼び出・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ闔橸ｿｽﾔ鯉ｿｽ・ｽ1・ｽｾゑｿｽ・ｽ・ｽ・ｽs・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽB', '短時間に複数回呼ばれても、最後の呼び出しだけが最終的に1回だけ実行されます。'
$content = $content -replace 'SoilPiles ・ｽﾌ撰ｿｽ・ｽ・ｽ・ｽｦ搾ｿｽ・ｽﾉ趣ｿｽ・ｽs・ｽ・ｽ・ｽﾜゑｿｽ・ｽi・ｽf・ｽo・ｽE・ｽ・ｽ・ｽX・ｽ・ｽ・ｽX・ｽL・ｽb・ｽv・ｽj・ｽB', 'SoilPiles の生成を即座に実行します（デバウンススキップ）。'
$content = $content -replace '・ｽ・ｽ・ｽ・ｽ・ｽI・ｽﾉ托ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽs・ｽ・ｽ・ｽK・ｽv・ｽﾈ場合・ｽﾉ使・ｽp・ｽ・ｽ・ｽﾜゑｿｽ・ｽB', '即時に実行する必要がある場合に使用します。'
$content = $content -replace '// ・ｽﾛ暦ｿｽ・ｽ・ｽ・ｽﾌデ・ｽo・ｽE・ｽ・ｽ・ｽX・ｽ・ｽ・ｽL・ｽ・ｽ・ｽ・ｽ・ｽZ・ｽ・ｽ', '// 保留中のデバウンスタイマーをキャンセル'
$content = $content -replace '// ・ｽN・ｽ・ｽ・ｽX・ｽﾌ先頭・ｽt・ｽﾟのフ・ｽB・ｽ\[・ｽ・ｽ・ｽh・ｽﾉ追会ｿｽ・ｽi・ｽ・ｽ・ｽ・ｽ・ｽﾌフ・ｽB・ｽ\[・ｽ・ｽ・ｽh・ｽﾌ近ゑｿｽ・ｽﾉ）', '// クラスの先頭付近のフィールドに追加（既存のフィールドの近くに）'
$content = $content -replace '・ｽE・ｽB・ｽ・ｽ・ｽh・ｽE・ｽX・ｽV・ｽ・ｽ・ｽf・ｽo・ｽE・ｽ・ｽ・ｽX・ｽt・ｽ・ｽ・ｽﾅ・ｿｽ・ｽN・ｽG・ｽX・ｽg・ｽ・ｽ・ｽﾜゑｿｽ・ｽB', 'ウィンドウ更新をデバウンスでリクエストします。'
$content = $content -replace '・ｽE・ｽB・ｽ・ｽ・ｽh・ｽE・ｽX・ｽV・ｽｦ搾ｿｽ・ｽﾉ趣ｿｽ・ｽs・ｽ・ｽ・ｽﾜゑｿｽ・ｽi・ｽf・ｽo・ｽE・ｽ・ｽ・ｽX・ｽ・ｽ・ｽX・ｽL・ｽb・ｽv・ｽj・ｽB', 'ウィンドウ更新を即座に実行します（デバウンススキップ）。'
$content = $content -replace '・ｽ_・ｽC・ｽA・ｽ・ｽ・ｽO・ｽ・ｽﾂゑｿｽ・ｽ・ｽ・ｽ・ｽﾈど、・ｽ・ｽ・ｽ・ｽ・ｽX・ｽV・ｽ・ｽ・ｽK・ｽv・ｽﾈ場合・ｽﾉ使・ｽp・ｽ・ｽ・ｽﾜゑｿｽ・ｽB', 'ダイアログを閉じた時など、即座更新が必要な場合に使用します。'
$content = $content -replace '// JsonSerializerOptions ・ｽ・ｽ・ｽL・ｽ・ｽ・ｽb・ｽV・ｽ・ｽ', '// JsonSerializerOptions をキャッシュ'
$content = $content -replace '// ・ｽX・ｽ・ｽ・ｽC・ｽ_・ｽ\[・ｽﾏ更・ｽ・ｽ・ｽﾉ再描・ｽ・ｽ', '// スライダー変更時に再描画'
$content = $content -replace '// ・ｽﾇ会ｿｽ: ・ｽR・ｽ}・ｽ・ｽ・ｽh・ｽX・ｽV・ｽ鼕・ｿｽw・ｽ・ｽ・ｽp', '// 追加: コマンド更新最適化用'
$content = $content -replace '// ・ｽ・ｽ・ｽt・ｽ・ｽ・ｽN・ｽV・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ "Command" ・ｽﾅ終・ｽ・ｽ驍ｷ・ｽﾗてのコ・ｽ}・ｽ・ｽ・ｽh・ｽv・ｽ・ｽ・ｽp・ｽe・ｽB・ｽ・ｽ唐・ｽ・ｽA', '// リフレクションで "Command" で終わる名前を持つすべてのコマンドプロパティを列挙し、'
$content = $content -replace '// CommunityToolkit ・ｽ・ｽ IRelayCommand ・ｽ・ｽ NotifyCanExecuteChanged\(\) ・ｽ・ｽ・ｽﾄび、', '// CommunityToolkit の IRelayCommand は NotifyCanExecuteChanged() を呼び、'
$content = $content -replace '// ・ｽ・ｽ・ｽO RelayCommand ・ｽ・ｽ・ｽ・ｽ RaiseCanExecuteChanged\(\) ・ｽ・ｽ・ｽﾄび出・ｽ・ｽ・ｽB', '// 旧来 RelayCommand には RaiseCanExecuteChanged() を呼び出す。'
$content = $content -replace '// CommunityToolkit ・ｽ・ｽ IRelayCommand ・ｽ・ｽD・ｽ謔ｵ・ｽﾄ茨ｿｽ・ｽ・ｽ', '// CommunityToolkit の IRelayCommand を優先して試す'
$content = $content -replace '// ・ｽ・ｽ・ｽO RelayCommand ・ｽ・ｽ RaiseCanExecuteChanged\(\) ・ｽ・ｽT・ｽ・ｽ・ｽﾄ呼び出・ｽ・ｽ', '// 旧来 RelayCommand の RaiseCanExecuteChanged() を探して呼び出す'
$content = $content -replace '// ・ｽﾝ奇ｿｽ・ｽ・ｽ・ｽﾌゑｿｽ・ｽ・ｽ NotifyCanExecuteChanged ・ｽ・ｽ・ｽ\\・ｽb・ｽh・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽi・ｽﾜゑｿｽﾈケ・ｽ\[・ｽX・ｽj', '// 念のため他の NotifyCanExecuteChanged メソッドがあれば試す（稀なケース）'
$content = $content -replace '// ・ｽﾂ別コ・ｽ}・ｽ・ｽ・ｽh・ｽﾌ擾ｿｽﾔ更・ｽV・ｽﾅ暦ｿｽO・ｽ・ｽ・ｽN・ｽ・ｽ・ｽﾄゑｿｽ・ｽ・ｽ・ｽﾍ托ｿｽ・ｽs・ｽ・ｽ・ｽ・ｽ', '// 個別コマンドの状態更新で例外が起きても継続する'
$content = $content -replace '// SetProperty ・ｽ・ｽ ObservableObject ・ｽﾌ・ｿｽ・ｽ\[・ｽe・ｽB・ｽ・ｽ・ｽe・ｽB・ｽ\(CommunityToolkit・ｽj', '// SetProperty は ObservableObject のユーティリティ(CommunityToolkit)'
$content = $content -replace '// VM ・ｽﾄア・ｽ^・ｽb・ｽ`・ｽﾈどはゑｿｽ・ｽ・ｽ・ｽﾅ茨ｿｽx・ｽ・ｽ・ｽ・ｽ・ｽs・ｽ・ｽ', '// VM でアタッチなどはここで一度だけ行う'
$content = $content -replace '// ・ｽﾋ托ｿｽ・ｽ・ｽ・ｽ・ｽUI・ｽX・ｽV・ｽE・ｽR・ｽ}・ｽ・ｽ・ｽh・ｽ・ｽﾔゑｿｽ・ｽﾜとめて行・ｽ・ｽ', '// 初期化後のUI更新・コマンド状態などをまとめて行う'
$content = $content -replace '// ・ｽK・ｽv・ｽﾈゑｿｽﾂ別プ・ｽ・ｽ・ｽp・ｽe・ｽB・ｽﾊ知', '// 必要な個別プロパティ通知'
$content = $content -replace '// ・ｽC・ｽ・ｽ・ｽ・ｽ: CurrentFilePath', '// 以前: CurrentFilePath'
$content = $content -replace '// ・ｽt・ｽ@・ｽC・ｽ・ｽ・ｽp・ｽX・ｽﾏ更・ｽﾉ費ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽi・ｽK・ｽv・ｽﾈゑｿｽj', '// ファイルパス変更に伴う状態変更（必要なら）'
$content = $content -replace '// ・ｽC・ｽ・ｽ・ｽ・ｽ: Canvas3DLayout', '// 以前: Canvas3DLayout'
$content = $content -replace '// ・ｽC・ｽ・ｽ・ｽ・ｽ: ・ｽA・ｽN・ｽV・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽv・ｽ・ｽ・ｽp・ｽe・ｽB・ｽ・ｽ・ｽi・ｽK・ｽv・ｽﾈゑｿｽj', '// 以前: アクション型プロパティ（必要なら）'
$content = $content -replace '// ・ｽC・ｽx・ｽ・ｽ・ｽg・ｽﾌ宣言', '// イベントの宣言'
$content = $content -replace '// ・ｽC・ｽx・ｽ・ｽ・ｽg・ｽｭ火ゑｿｽ・ｽ驛・ｿｽ\\・ｽb・ｽh', '// イベントを発火するメソッド'
$content = $content -replace '// ・ｽR・ｽ}・ｽ・ｽ・ｽh・ｽﾌ趣ｿｽ・ｽ・ｽ', '// コマンドの実装'
$content = $content -replace '// ・ｽﾇ会ｿｽ: ・ｽr・ｽ・ｽ・ｽ\[・ｽ・ｽ・ｽ・ｽp・ｽf・ｽ・ｽ・ｽQ・ｽ\[・ｽg・ｽi・ｽR・ｽ\[・ｽh・ｽr・ｽn・ｽC・ｽ・ｽ・ｽh・ｽ・ｽ・ｽﾅセ・ｽb・ｽg・ｽj', '// 追加: ビュー操作用デリゲート（コードビハインド側でセット）'
$content = $content -replace '// ・ｽY・ｽ\[・ｽ・ｽ・ｽt・ｽB・ｽb・ｽg', '// ズームフィット'
$content = $content -replace '// ・ｽ・ｽ=-90, ・ｽ・ｽ=90', '// θ=-90, φ=90'
$content = $content -replace '// XY・ｽ・ｽ・ｽ・ｽ', '// XY平面'
$content = $content -replace '// YZ・ｽ・ｽ・ｽ・ｽ', '// YZ平面'
$content = $content -replace '// XZ・ｽ・ｽ・ｽ・ｽ', '// XZ平面'
$content = $content -replace '// ・ｽA・ｽC・ｽ\\・ｽ・ｽ', '// アイソメ'
$content = $content -replace '// ・ｽC・ｽx・ｽ・ｽ・ｽg・ｽn・ｽ・ｽ・ｽh・ｽ・ｽ・ｽﾌ趣ｿｽ・ｽ・ｽ', '// イベントハンドラの実装'
$content = $content -replace 'SettlementSoilLayer ・ｽﾍ適・ｽﾘな・ｿｽ・ｽf・ｽ・ｽ・ｽN・ｽ・ｽ・ｽX・ｽﾉ置・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾄゑｿｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ', 'SettlementSoilLayer は適切なモデルクラスに置き換えてください'
$content = $content -replace '・ｽ・ｽ・ｽ\[Z・ｽﾍ茨ｿｽﾂ擾ｿｽﾌセ・ｽ・ｽ・ｽﾌ値・ｽ・ｽ闖ｬ・ｽ・ｽ・ｽ・ｽ・ｽﾈゑｿｽ・ｽ・ｽﾎなゑｿｽﾜゑｿｽ・ｽ・ｽB', '下端Zは一つ上のセルの値より小さくなければなりません。'
$content = $content -replace '・ｽ・ｽ・ｽﾍエ・ｽ・ｽ・ｽ\[', '入力エラー'
$content = $content -replace '// ・ｽs・ｽﾔ搾ｿｽ・ｽ・ｽﾝ抵ｿｽ', '// 行番号を設定'
$content = $content -replace '// ・ｽY・ｽz・ｽu・ｽX・ｽV・ｽ・ｽ・ｽX・ｽV・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 杭配置更新時更新メソッド'
$content = $content -replace '// ・ｽo・ｽC・ｽ・ｽ・ｽf・ｽB・ｽ・ｽ・ｽO・ｽ\\・ｽ\[・ｽX・ｽﾌ更・ｽV', '// バインディングソースの更新'
$content = $content -replace '// ・ｽﾏ更: ・ｽf・ｽo・ｽE・ｽ・ｽ・ｽX・ｽt・ｽ・ｽ・ｽﾅ更・ｽV', '// 変更: デバウンスで更新'
$content = $content -replace '// ・ｽE・ｽB・ｽ・ｽ・ｽh・ｽE・ｽﾌ更・ｽV', '// ウィンドウの更新'
$content = $content -replace '// ・ｽf・ｽ・ｽ・ｽQ・ｽ\[・ｽg・ｽ・ｽﾊじてコ・ｽ\[・ｽh・ｽr・ｽn・ｽC・ｽ・ｽ・ｽh・ｽﾌ・ｿｽ・ｽ\\・ｽb・ｽh・ｽ・ｽ・ｽﾄび出・ｽ・ｽ', '// デリゲートを通じてコードビハインドのメソッドを呼び出す'
$content = $content -replace '// ・ｽR・ｽ・ｽ・ｽN・ｽV・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾌの変更・ｽﾊ知', '// コレクション自体の変更通知'
$content = $content -replace '// ・ｽY・ｽ・ｽ・ｽﾍ更・ｽV・ｽ・ｽ・ｽX・ｽV・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 杭軸力更新時更新メソッド'
$content = $content -replace '// ・ｽﾏ更・ｽ・ｽi・ｽﾈ会ｿｽ・ｽﾌ箇擾ｿｽ・ｽﾅ適・ｽp・ｽj', '// 変更済（追加の箇所で適用）'
$content = $content -replace '// ・ｽO・ｽ・ｽY・ｽX・ｽV・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 前後杭更新メソッド'
$content = $content -replace '// ・ｽY・ｽz・ｽu・ｽ\\・ｽﾒ集・ｽJ・ｽn・ｽ・ｽ・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 杭配置表編集開始時メソッド'
$content = $content -replace '// ・ｽv・ｽf・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽm・ｽF・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 要素分割解除確認メソッド'
$content = $content -replace '・ｽ・ｽﾒ集、・ｽm・ｽ・ｽ', 'を編集、確定'
$content = $content -replace '・ｽ・ｽ・ｽ・ｽﾏみの要素・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾑゑｿｽA', '入力済みの要素分割および、'
$content = $content -replace '・ｽ・ｽ・ｽﾍ結・ｽﾊ・ｽ・ｽ・ｽ・ｽ・ｽﾝ托ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽﾍ・ｿｽ・ｽ・ｽﾍ結・ｽﾊ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽK・ｽv・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽB', '\\n解析結果が存在する場合は解析結果を削除する必要があります。'
$content = $content -replace '・ｽ・ｽ・ｽ\[Z', '下端Z'
$content = $content -replace '・ｽY・ｽz・ｽu', '杭配置'
$content = $content -replace '・ｽY・ｽﾌ', '杭体'
$content = $content -replace '・ｽ・ｽ・ｽ・ｽ', '根入部'
$content = $content -replace '・ｽn・ｽﾕ', '地盤'
$content = $content -replace '・ｽm・ｽF', '確認'
$content = $content -replace '・ｽG・ｽ・ｽ・ｽ\[', 'エラー'
$content = $content -replace '・ｽﾛ托ｿｽ', '保存'
$content = $content -replace '・ｽﾇ搾ｿｽ', '読込'
$content = $content -replace '・ｽ・ｽ・ｽ', '情報'
$content = $content -replace '・ｽQ・ｽY', '群杭'
$content = $content -replace '・ｽﾍ前・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ\[・ｽh・ｽﾉゑｿｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽH', '解析前処理モードにしますか？'
$content = $content -replace '・ｽY・ｽz・ｽu・ｽf・ｽ\[・ｽ^・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽB', '杭配置データがありません。'
$content = $content -replace '・ｽQ・ｽY・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾍ用・ｽﾌ土・ｽw・ｽ・ｽ1・ｽw・ｽﾈ擾ｿｽK・ｽv・ｽﾅゑｿｽ・ｽB', '群杭沈下解析用の土層が1層以上必要です。'
$content = $content -replace '・ｽX・ｽ^・ｽC・ｽ・ｽ・ｽu・ｽ・ｽ・ｽi・ｽ\[・ｽﾌ近趣ｿｽ・ｽ・ｽ・ｽﾉゑｿｽ・ｽ・ｽﾍゑｿｽ・ｽI・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', 'スタインブレナーの近似式による解析が終了しました。'
$content = $content -replace '・ｽﾛ托ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', '保存が完了しました。'
$content = $content -replace '・ｽﾛ托ｿｽ・ｽﾉ趣ｿｽ・ｽs・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', '保存に失敗しました。'
$content = $content -replace '・ｽt・ｽ@・ｽC・ｽ・ｽ・ｽﾌ読搾ｿｽ・ｽﾉ趣ｿｽ・ｽs・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', 'ファイルの読込に失敗しました。'
$content = $content -replace '・ｽﾇ搾ｿｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', '読込が完了しました。'
$content = $content -replace '・ｽﾇ搾ｿｽ・ｽﾉ趣ｿｽ・ｽs・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', '読込に失敗しました。'
$content = $content -replace '・ｽﾇ搾ｿｽ・ｽG・ｽ・ｽ・ｽ\[', '読込エラー'
$content = $content -replace '・ｽt・ｽ@・ｽC・ｽ・ｽ・ｽﾇ搾ｿｽ・ｽ・ｽ・ｽﾉエ・ｽ・ｽ・ｽ\[・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾜゑｿｽ・ｽ・ｽ・ｽB', 'ファイル読込にエラーが発生しました。'
$content = $content -replace '// ・ｽY・ｽz・ｽu・ｽ\\・ｽ}・ｽE・ｽX・ｽE・ｽ{・ｽ^・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ\\・ｽb・ｽh', '// 杭配置表マウス右ボタン押メソッド'
$content = $content -replace '// ・ｽ}・ｽE・ｽX・ｽﾊ置・ｽ・ｽ ContextMenu ・ｽ・ｽ\\・ｽ・ｽ', '// マウス位置で ContextMenu を表示'
$content = $content -replace '// ・ｽJ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ`・ｽF・ｽb・ｽN・ｽ・ｽ・ｽA・ｽK・ｽX・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽs・ｽ・ｽ', '// カラム名をチェックし、適宜処理を行う'
$content = $content -replace '// ・ｽ・ｽﾍ奇ｿｽ・ｽ・ｽ・ｽ・ｽ \(・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽ・ｽﾉ追会ｿｽ\)', '// 解析結果 (ログウィンドウ表示に追加)'
$content = $content -replace '・ｽ・ｽﾍ鯉ｿｽ・ｽﾊテ・ｽ\[・ｽu・ｽ・ｽ・ｽﾄ撰ｿｽ・ｽ・ｽ', '解析結果テーブルで生成'
$content = $content -replace '・ｽC・ｽﾓ具ｿｽ`', '一括入力'
$content = $content -replace '・ｽﾂ別十・ｽ・ｽ', '個別入力'

# Write back to file
$content | Set-Content -Path $filePath -Encoding UTF8 -NoNewline

Write-Host "Garbled text fixed successfully!"

