<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>	

  <ItemGroup>
    <Compile Remove="PileNode.cs" />
    <Compile Remove="RestoringForce.cs" />
    <Compile Remove="ViewModels\LoadCaseCommon.cs" />
  </ItemGroup>	

  <ItemGroup>
    <None Remove="Icons\ActiveAll.svg" />
    <None Remove="Icons\AddElementMode.svg" />
    <None Remove="Icons\AnalysisResultVisilbe.svg" />
    <None Remove="Icons\ArrowHeadDia.svg" />
    <None Remove="Icons\ArrowHeadLength.svg" />
    <None Remove="Icons\ArrowLength.svg" />
    <None Remove="Icons\ArrowVisible.svg" />
    <None Remove="Icons\AxesVisible.svg" />
    <None Remove="Icons\BoundaryCondition.svg" />
    <None Remove="Icons\BubbleDia.svg" />
    <None Remove="Icons\BubbleVisible.svg" />
    <None Remove="Icons\Cancel.svg" />
    <None Remove="Icons\CsvFileOutput.svg" />
    <None Remove="Icons\DeformedElementVisible.svg" />
    <None Remove="Icons\DeselectAll.svg" />
    <None Remove="Icons\Display.svg" />
    <None Remove="Icons\DocxFileOutput.svg" />
    <None Remove="Icons\ElementNo.svg" />
    <None Remove="Icons\ElementVisible.svg" />
    <None Remove="Icons\FrontView.svg" />
    <None Remove="Icons\Grid.png" />
    <None Remove="Icons\GridVisible.svg" />
    <None Remove="Icons\HorizontalRotation.svg" />
    <None Remove="Icons\InvertActive.svg" />
    <None Remove="Icons\IsAxialForceVisible.svg" />
    <None Remove="Icons\IsElementLocalAxesVisible.svg" />
    <None Remove="Icons\IsElementLocalAxesVisible_1.svg" />
    <None Remove="Icons\IsEmbedmentBoxVisible.svg" />
    <None Remove="Icons\IsForcedDispVisible.svg" />
    <None Remove="Icons\IsFrontPileVisible.svg" />
    <None Remove="Icons\IsGridVisible.svg" />
    <None Remove="Icons\IsGroupPileFactorVisible.svg" />
    <None Remove="Icons\IsLoadingVisible.svg" />
    <None Remove="Icons\IsometricView.svg" />
    <None Remove="Icons\IsPileDiaSpacingRatioVisible.svg" />
    <None Remove="Icons\IsPileRefVisible.svg" />
    <None Remove="Icons\IsPileTopLevelVisible.svg" />
    <None Remove="Icons\IsRigidConnectionVisible.svg" />
    <None Remove="Icons\IsSoilRefVisible.svg" />
    <None Remove="Icons\LabelVisible.svg" />
    <None Remove="Icons\LateralLoadActionPointVisible.svg" />
    <None Remove="Icons\LoadingPlaneSelected.svg" />
    <None Remove="Icons\LoadingPlaneVisible.svg" />
    <None Remove="Icons\MergeElements.svg" />
    <None Remove="Icons\MergeNodes.svg" />
    <None Remove="Icons\NodeNo.svg" />
    <None Remove="Icons\NodeVisible.svg" />
    <None Remove="Icons\OpenFile.svg" />
    <None Remove="Icons\PileTopSelected.svg" />
    <None Remove="Icons\Play.svg" />
    <None Remove="Icons\PostAnalysisMode.svg" />
    <None Remove="Icons\PreAnalysisMode.svg" />
    <None Remove="Icons\Redo.svg" />
    <None Remove="Icons\Resume.svg" />
    <None Remove="Icons\RightView.svg" />
    <None Remove="Icons\SaveFile.svg" />
    <None Remove="Icons\Scale.svg" />
    <None Remove="Icons\SelectAll.svg" />
    <None Remove="Icons\SelectedActive.svg" />
    <None Remove="Icons\SelectedInactive.svg" />
    <None Remove="Icons\ShrinkElementMode.svg" />
    <None Remove="Icons\SoilLayerVisible.svg" />
    <None Remove="Icons\SplitElementByNodes.svg" />
    <None Remove="Icons\Stop.svg" />
    <None Remove="Icons\SurroundingSoilVisible.svg" />
    <None Remove="Icons\TickMarkVisible.svg" />
    <None Remove="Icons\TopView.svg" />
    <None Remove="Icons\Undo.svg" />
    <None Remove="Icons\VerticalRotation.svg" />
    <None Remove="Icons\WireFrameVisible.svg" />
    <None Remove="Icons\ZoomFit.svg" />
    <None Remove="Icons\？1.svg" />
    <None Remove="Icons\？2.png" />
    <None Remove="Icons\？2.svg" />
    <None Remove="Models\PileLibrary\CaptainPileTensionBarPCD_circle.csv" />
    <None Remove="Models\PileLibrary\CaptainPileTensionBarPCD_square.csv" />
    <None Remove="Models\PileLibrary\FTCap.csv" />
    <None Remove="Models\PileLibrary\PCRing.csv" />
    <None Remove="Views\help.html" />
  </ItemGroup>	

  <ItemGroup>
    <Content Include="Models\PileLibrary\CaptainPileTensionBarPCD_circle.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\CaptainPileTensionBarPCD_square.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\FTCap.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\PCRing.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Help\help.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Icons\ActiveAll.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\AddElementMode.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\AnalysisResultVisilbe.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ArrowHeadDia.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ArrowHeadLength.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ArrowLength.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ArrowVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\AxesVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\BoundaryCondition.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\BubbleDia.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\BubbleVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Cancel.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\CsvFileOutput.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\DeformedElementVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\DeselectAll.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Display.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\DocxFileOutput.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ElementNo.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ElementVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\FrontView.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Grid.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\GridVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\HorizontalRotation.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\InvertActive.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsAxialForceVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsElementLocalAxesVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsElementLocalAxesVisible_1.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsEmbedmentBoxVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsForcedDispVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsFrontPileVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsGridVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsGroupPileFactorVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsLoadingVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsometricView.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsPileDiaSpacingRatioVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsPileRefVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsPileTopLevelVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsRigidConnectionVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\IsSoilRefVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\LabelVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\LateralLoadActionPointVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\LoadingPlaneSelected.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\LoadingPlaneVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\MergeElements.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\MergeNodes.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\NodeNo.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\NodeVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\OpenFile.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\PileTopSelected.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Play.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\PostAnalysisMode.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\PreAnalysisMode.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Redo.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Resume.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\RightView.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SaveFile.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Scale.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SelectAll.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SelectedActive.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SelectedInactive.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ShrinkElementMode.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SoilLayerVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SplitElementByNodes.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Stop.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\SurroundingSoilVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\TickMarkVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\TopView.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\Undo.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\VerticalRotation.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\WireFrameVisible.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\ZoomFit.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\？1.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\？2.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Icons\？2.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Content Include="Models\PileLibrary\JIS_A_5525_2019.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\JIS_G_3444.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\pile_library_SteelPile.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\pile_library_PHC.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\pile_library_PRC.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\pile_library_SC.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Models\PileLibrary\PresetSettlementParameterSet.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ACadSharp" Version="3.2.22" />
    <PackageReference Include="CSparse" Version="4.3.0" />
    <PackageReference Include="HelixToolkit.Geometry" Version="3.1.1" />
    <PackageReference Include="HelixToolkit.Maths" Version="3.1.1" />
    <PackageReference Include="HelixToolkit.SharpDX.Core" Version="2.27.3" />
    <PackageReference Include="HelixToolkit.SharpDX.Core.Wpf" Version="2.27.3" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.1" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Rhino3dm" Version="8.17.0" />
    <PackageReference Include="ScottPlot" Version="5.1.57" />
    <PackageReference Include="ScottPlot.WPF" Version="5.1.57" />
    <PackageReference Include="SharpVectors" Version="1.8.5" />
    <PackageReference Include="SharpVectors.Wpf" Version="1.8.5" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
    <PackageReference Include="Svg.Skia" Version="3.2.1" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.6.0-preview3.19128.7" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="6.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="WebView2.Runtime.X64" Version="142.0.3595.80" />
    <PackageReference Include="WpfMath" Version="2.1.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="NikkenLogo\170703_Nikken_Brandmark_Tagline.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.4" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.3.0" />
    <PackageReference Include="HarfBuzzSharp" Version="8.3.1.2" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.macOS" Version="8.3.1.2" />
    <PackageReference Include="HarfBuzzSharp.NativeAssets.Win32" Version="8.3.1.2" />
    <PackageReference Include="HelixToolkit" Version="3.1.1" />
    <PackageReference Include="LiveChartsCore" Version="2.0.0-rc4.5" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView" Version="2.0.0-rc4.5" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc4.5" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageReference Include="OpenTK" Version="5.0.0-pre.13" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="5.0.0-pre.1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
</Project>