<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="PileLibrary\JIS_A_5525_2019.csv" />
    <Resource Include="PileLibrary\JIS_G_3444.csv" />
    <Resource Include="PileLibrary\pile_library_SteelPile.csv" />
    <Resource Include="PileLibrary\pile_library_PHC.csv" />
    <Resource Include="PileLibrary\pile_library_PRC.csv" />
    <Resource Include="PileLibrary\pile_library_SC.csv" />
    <Resource Include="PileLibrary\PresetSettlementParameterSet.csv" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HelixToolkit.SharpDX.Core.Wpf" Version="2.25.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="8.0.0" />
    <PackageReference Include="Microsoft.Bcl.HashCode" Version="1.1.1" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.6" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Text.Encodings.Web" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.3" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="NikkenLogo\170703_Nikken_Brandmark_Tagline.jpg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="32.0.3" />
    <PackageReference Include="Cyotek.Drawing.BitmapFont" Version="2.0.4" />
    <PackageReference Include="Dirkster.AvalonDock" Version="4.72.1" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.72.1" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.0.2" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.0.2" />
    <PackageReference Include="HelixToolkit" Version="2.25.0" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageReference Include="OpenTK" Version="4.8.2" />
    <PackageReference Include="OpenTK.GLWpfControl" Version="4.3.1" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="SharpDX.D3DCompiler" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct2D1" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D11" Version="4.2.0" />
    <PackageReference Include="SharpDX.Direct3D9" Version="4.2.0" />
    <PackageReference Include="SharpDX.DXGI" Version="4.2.0" />
    <PackageReference Include="SharpDX.Mathematics" Version="4.2.0" />
    <PackageReference Include="SkiaSharp" Version="3.0.0-preview.3.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.macOS" Version="3.0.0-preview.3.1" />
    <PackageReference Include="SkiaSharp.NativeAssets.Win32" Version="3.0.0-preview.3.1" />
    <PackageReference Include="SkiaSharp.Views.Desktop.Common" Version="3.0.0-preview.3.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="2.88.8" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>
</Project>